export const PHONE_PREFIXES = [
  // Europa
  { code: '+34', label: 'ES' },
  { code: '+44', label: 'UK' },
  { code: '+33', label: 'FR' },
  { code: '+49', label: 'DE' },
  { code: '+39', label: 'IT' },
  { code: '+351', label: 'PT' },
  { code: '+31', label: 'NL' },
  { code: '+32', label: 'BE' },
  { code: '+41', label: 'CH' },
  { code: '+43', label: 'AT' },
  { code: '+46', label: 'SE' },
  { code: '+47', label: 'NO' },
  { code: '+45', label: 'DK' },
  { code: '+358', label: 'FI' },
  { code: '+353', label: 'IE' },
  { code: '+48', label: 'PL' },
  { code: '+420', label: 'CZ' },
  { code: '+421', label: 'SK' },
  { code: '+36', label: 'HU' },
  { code: '+40', label: 'RO' },
  { code: '+359', label: 'BG' },
  { code: '+30', label: 'GR' },
  { code: '+385', label: 'HR' },
  { code: '+386', label: 'SI' },
  { code: '+381', label: 'RS' },
  { code: '+370', label: 'LT' },
  { code: '+371', label: 'LV' },
  { code: '+372', label: 'EE' },
  { code: '+380', label: 'UA' },
  { code: '+352', label: 'LU' },
  { code: '+356', label: 'MT' },
  { code: '+354', label: 'IS' },
  { code: '+376', label: 'AD' },
  { code: '+377', label: 'MC' },
  { code: '+378', label: 'SM' },
  { code: '+423', label: 'LI' },
  // América del Norte
  { code: '+1-US', label: 'US' },
  { code: '+1-CA', label: 'CA' },
  { code: '+52', label: 'MX' },
  // América Central
  { code: '+501', label: 'BZ' },
  { code: '+502', label: 'GT' },
  { code: '+503', label: 'SV' },
  { code: '+504', label: 'HN' },
  { code: '+505', label: 'NI' },
  { code: '+506', label: 'CR' },
  { code: '+507', label: 'PA' },
  // Caribe
  { code: '+53', label: 'CU' },
  { code: '+509', label: 'HT' },
  { code: '+1-DO', label: 'DO' },
  { code: '+1-JM', label: 'JM' },
  { code: '+1-TT', label: 'TT' },
  { code: '+1-BB', label: 'BB' },
  { code: '+1-PR', label: 'PR' },
  // América del Sur
  { code: '+55',  label: 'BR' },
  { code: '+54',  label: 'AR' },
  { code: '+56',  label: 'CL' },
  { code: '+57',  label: 'CO' },
  { code: '+58',  label: 'VE' },
  { code: '+51',  label: 'PE' },
  { code: '+593', label: 'EC' },
  { code: '+591', label: 'BO' },
  { code: '+595', label: 'PY' },
  { code: '+598', label: 'UY' },
  { code: '+592', label: 'GY' },
  { code: '+597', label: 'SR' },
]